const TEST_PORT = '4441';
const TEST_CALCULATOR_PORT = '4442';
const TEST_CONVERTER_PORT = '4443';

process.env = Object.assign(process.env, {
  PORT: TEST_PORT,
  CALCULATOR_PORT: TEST_CALCULATOR_PORT,
  CONVERTER_PORT: TEST_CONVERTER_PORT,
  API_HOST: `localhost:${TEST_PORT}`,
  CALCULATOR_API_HOST: `localhost:${TEST_CALCULATOR_PORT}`,
  CONVERTER_API_HOST: `localhost:${TEST_CONVERTER_PORT}`
});
